# Generated by Django 3.2.4 on 2021-10-31 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(3000)], verbose_name='year')),
                ('pi', models.CharField(max_length=255)),
                ('contact', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('permission', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Guest', 'Guest')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Center_Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lab_label', models.CharField(choices=[('BSCMC', 'BSCMC'), ('SSL', 'SSL'), ('MaCS', 'MaCS'), ('AML (CAES)', 'AML (CAES)'), ('AML (MSMSE)', 'AML (MSMSE)'), ('Materials Teaching Lab', 'Materials Teaching Lab'), ('Keck', 'Keck'), ('Other MSE Labs', 'Other MSE Labs'), ('Phys-Chem-Biol-Other', 'Phys-Chem-Biol-Other'), ('IML', 'IML')], max_length=200, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_center_lab', to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('Processing', 'Processing'), ('Structural', 'Structural'), ('Chemical', 'Chemical'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Thermal', 'Thermal'), ('Other', 'Other')], max_length=200, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipCat', to='equipment.equipment')),
            ],
        ),
    ]
