name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Make executable
      run: chmod +x ./build.sh
    - name: Install dependencies and Analysing the code with pylint
      run: ./build.sh
